services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/perform
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: aboba
      MIGRATION_ENABLED: "true"
      PAGINATION_DEFAULT_PAGE_SIZE: "15"
      PAGINATION_MAX_PAGE_SIZE: "75"
      SCROLL_DEFAULT_LIMIT: "15"
      SCROLL_MAX_LIMIT: "75"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: perform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aboba
    volumes:
      - .pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d perform -U postgres"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
