services:
  eureka-server:
    build:
      context: .
      dockerfile: docker/eureka-server.Dockerfile
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --silent --fail eureka-server:8761/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  config-server:
    build:
      context: .
      dockerfile: docker/config-server.Dockerfile
    ports:
      - "8800:8800"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/
    healthcheck:
      test: "curl --silent --fail config-server:8800/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/

  cdr-service:
    build:
      context: .
      dockerfile: docker/cdr-service.Dockerfile
    depends_on:
      eureka-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    environment:
      EUREKA_URL: http://eureka-server:8761/eureka/

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: perform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aboba
    ports:
      - "5433:5432"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -d perform -U postgres"
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

volumes:
  pgdata:
