apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  ports:
    - name: "8800"
      port: 8800
      protocol: TCP
      targetPort: 8800
    - name: "7000"
      port: 7000
      protocol: TCP
      targetPort: 7000
  selector:
    app: notification-service
  type: LoadBalancer
