apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          env:
            - name: EUREKA_URL
              value: http://eureka-server:8761/eureka/eureka/
            - name: CONFIG_URL
              value: http://config-server:8800/
            - name: ACTIVE_PROFILE
              value: test
          volumeMounts:
            - name: key
              readOnly: true
              mountPath: /app/.key
          resources:
            requests:
              cpu: "0.2"
              memory: 600Mi
            limits:
              cpu: "1.0"
              memory: 900Mi
      volumes:
        - name: key
          secret:
            secretName: key
