server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: @spring.profiles.active@

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}