spring:
  application:
    name: gateway
  profiles:
    active: ${ACTIVE_PROFILE:test}
  config:
    import: 'configserver:'
  cloud:
    config:
      name: ${spring.application.name}
      uri: ${CONFIG_URL}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
        default-filters:
          - RewritePath=${CONTEXT_PATH:/}.*?/(?<remaining>.*), /$\{remaining}

springdoc:
  api-docs:
    enabled: true
    path: /v3/openapi
  swagger-ui:
    path: /swagger-ui
    enabled: true
    urls:
      - url: /file-service/v3/openapi
        name: File Service
      - url: /cdr-service/v3/openapi
        name: Cdr Service
      - url: /billing-service/v3/openapi
        name: Billing Service
      - url: /account-service/v3/openapi
        name: Account Service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}