api:
  prefix: /api/v1
  access:
    username: test
    password: test

app:
  openapi:
    prefix: /gateway
  kafka:
    url: "kafka:9092"
    group-id: cdr-service
    topics:
      file-uploaded: file-upload
      file-upload-cancel: file-upload-cancel
      cdr-file-parsed: cdr-file-parsed
      cdr-file-cancel: cdr-file-cancel
  socket:
    file-service-port: 7000

server:
  port: 8082
spring:
  r2dbc:
    url: ${DATASOURCE_URL:r2dbc:postgresql://db:5432/perform}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:aboba}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:.key}

springdoc:
  api-docs:
    path: /v3/openapi

reactive:
  feign:
    client:
      config:
        file-service:
          retry:
            builder: reactivefeign.retry.BasicReactiveRetryPolicy.Builder
            args:
              maxRetries: 3
              backoffInMs: 50