api:
  prefix: /api/v1

server:
  port: 8082
spring:
  r2dbc:
    url: ${DATASOURCE_URL:r2dbc:postgresql://db:5432/perform}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:aboba}
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:.key}

reactive:
  feign:
    client:
      config:
        file-service:
          retry:
            builder: reactivefeign.retry.BasicReactiveRetryPolicy.Builder
            args:
              maxRetries: 3
              backoffInMs: 900