api:
  prefix: /api/v1
  access:
    username: test
    password: test

app:
  kafka:
    url: "kafka:9092"
    group-id: file-service
    topics:
      file-uploaded: file-upload
      file-upload-cancel: file-upload-cancel

server:
  port: 8083
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://db:5432/perform}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:aboba}

  rsocket:
    server:
      transport: websocket
      port: 7000

jwt:
  private-key-path: ${JWT_PRIVATE_KEY_PATH:.key}

springdoc:
  api-docs:
    path: /v3/openapi
