spring:
  application:
    name: account-service
  profiles:
    active: @spring.profiles.active@
  config:
    import: 'configserver:'
  cloud:
    config:
      name: ${spring.application.name}
      uri: ${CONFIG_URL}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 10

eureka:
  instance:
    hostname: account-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}