apiVersion: v1
kind: Service
metadata:
  name: cdr-service
  labels:
    app: cdr-service
spec:
  ports:
    - port: 8800
      protocol: TCP
      targetPort: 8800
  selector:
    app: cdr-service
  type: LoadBalancer
