server:
  port: 8761
  servlet:
    contextPath: ${CONTEXT_PATH:/}

spring:
  application:
    name: eureka-server
  profiles:
    active: @spring.profiles.active@


eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false