apiVersion: v1
kind: Service
metadata:
  name: config-server
  labels:
    app: config-server
spec:
  ports:
    - port: 8800
      protocol: TCP
      targetPort: 8800
  selector:
    app: config-server
  type: LoadBalancer
