name: publish

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    name: publish service images
    runs-on: ubuntu-latest
    environment: ghcr-publish
    strategy:
      matrix:
        service:
          - account-service
          - billing-service
          - cdr-service
          - config-server
          - eureka-server
          - file-service
          - gateway
          - notification-service
    steps:
      - uses: actions/checkout@v3
      - name: setup image name
        run: |
          echo "IMAGE_NAME=${GITHUB_ACTOR,,}/${{ matrix.service }}" >>${GITHUB_ENV}
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: build & publish image
        run: |
          docker build . --file ./docker/${{ matrix.service }}.Dockerfile --tag ${{ env.REGISTRY }}/${IMAGE_NAME}:latest --tag ${{ env.REGISTRY }}/${IMAGE_NAME}:${{ github.ref_name }}
          docker push ${{ env.REGISTRY }}/${IMAGE_NAME}
